# This is a basic workflow to help you get started with Actions

name: package

# Controls when the action will run. Triggers the workflow on push or pull
# request events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build Debian package
        uses: dawidd6/action-debian-package@v1.0.0

      - name: Upload math result for job 1
        uses: actions/upload-artifact@v2
        with:
          path: "/home/runner/work/rchat/rchat/*.deb"
